export type CountryRecord = {
  alpha2: string;
  alpha3: string;
  numeric: string;
  aliases?: string[];
};

export const countries: CountryRecord[] = [
  { alpha2: "AF", alpha3: "AFG", numeric: "004" },
  { alpha2: "AL", alpha3: "ALB", numeric: "008" },
  { alpha2: "DZ", alpha3: "DZA", numeric: "012" },
  { alpha2: "AD", alpha3: "AND", numeric: "020" },
  { alpha2: "AO", alpha3: "AGO", numeric: "024" },
  { alpha2: "AR", alpha3: "ARG", numeric: "032" },
  { alpha2: "AM", alpha3: "ARM", numeric: "051" },
  { alpha2: "AU", alpha3: "AUS", numeric: "036", aliases: ["aussie", "australya"] },
  { alpha2: "AT", alpha3: "AUT", numeric: "040", aliases: ["austria", "avusturya"] },
  { alpha2: "AZ", alpha3: "AZE", numeric: "031", aliases: ["azerbaycan"] },
  { alpha2: "BS", alpha3: "BHS", numeric: "044" },
  { alpha2: "BH", alpha3: "BHR", numeric: "048" },
  { alpha2: "BD", alpha3: "BGD", numeric: "050" },
  { alpha2: "BY", alpha3: "BLR", numeric: "112", aliases: ["belarus", "beyaz rusya"] },
  { alpha2: "BE", alpha3: "BEL", numeric: "056" },
  { alpha2: "BZ", alpha3: "BLZ", numeric: "084" },
  { alpha2: "BJ", alpha3: "BEN", numeric: "204" },
  { alpha2: "BT", alpha3: "BTN", numeric: "064" },
  { alpha2: "BO", alpha3: "BOL", numeric: "068" },
  { alpha2: "BA", alpha3: "BIH", numeric: "070", aliases: ["bosnia", "bosna", "bosna hersek"] },
  { alpha2: "BW", alpha3: "BWA", numeric: "072" },
  { alpha2: "BR", alpha3: "BRA", numeric: "076", aliases: ["brezilya"] },
  { alpha2: "BN", alpha3: "BRN", numeric: "096" },
  { alpha2: "BG", alpha3: "BGR", numeric: "100", aliases: ["bulgaristan"] },
  { alpha2: "BF", alpha3: "BFA", numeric: "854" },
  { alpha2: "BI", alpha3: "BDI", numeric: "108" },
  { alpha2: "KH", alpha3: "KHM", numeric: "116", aliases: ["cambodia", "kambocya"] },
  { alpha2: "CM", alpha3: "CMR", numeric: "120" },
  { alpha2: "CA", alpha3: "CAN", numeric: "124", aliases: ["kanada"] },
  { alpha2: "CV", alpha3: "CPV", numeric: "132" },
  { alpha2: "CF", alpha3: "CAF", numeric: "140" },
  { alpha2: "TD", alpha3: "TCD", numeric: "148", aliases: ["chad", "cad"] },
  { alpha2: "CL", alpha3: "CHL", numeric: "152", aliases: ["sili"] },
  { alpha2: "CN", alpha3: "CHN", numeric: "156", aliases: ["china", "cin"] },
  { alpha2: "CO", alpha3: "COL", numeric: "170", aliases: ["kolombiya"] },
  { alpha2: "KM", alpha3: "COM", numeric: "174" },
  { alpha2: "CG", alpha3: "COG", numeric: "178", aliases: ["congo"] },
  {
    alpha2: "CD",
    alpha3: "COD",
    numeric: "180",
    aliases: ["dr congo", "democratic republic of congo", "kongo demokratik cumhuriyeti"],
  },
  { alpha2: "CR", alpha3: "CRI", numeric: "188", aliases: ["kosta rika"] },
  { alpha2: "HR", alpha3: "HRV", numeric: "191", aliases: ["croatia", "hirvatistan"] },
  { alpha2: "CU", alpha3: "CUB", numeric: "192" },
  { alpha2: "CY", alpha3: "CYP", numeric: "196", aliases: ["kibris", "cyprus"] },
  {
    alpha2: "CZ",
    alpha3: "CZE",
    numeric: "203",
    aliases: ["czechia", "czech republic", "cekya", "cek cumhuriyeti"],
  },
  { alpha2: "DK", alpha3: "DNK", numeric: "208", aliases: ["denmark", "danimarka"] },
  { alpha2: "DJ", alpha3: "DJI", numeric: "262" },
  { alpha2: "DO", alpha3: "DOM", numeric: "214" },
  { alpha2: "EC", alpha3: "ECU", numeric: "218", aliases: ["ekvador"] },
  { alpha2: "EG", alpha3: "EGY", numeric: "818", aliases: ["misir"] },
  { alpha2: "SV", alpha3: "SLV", numeric: "222" },
  { alpha2: "GQ", alpha3: "GNQ", numeric: "226" },
  { alpha2: "ER", alpha3: "ERI", numeric: "232" },
  { alpha2: "EE", alpha3: "EST", numeric: "233", aliases: ["estonya"] },
  { alpha2: "SZ", alpha3: "SWZ", numeric: "748", aliases: ["eswatini", "swaziland"] },
  { alpha2: "ET", alpha3: "ETH", numeric: "231", aliases: ["ethiopia", "etiyopya"] },
  { alpha2: "FJ", alpha3: "FJI", numeric: "242" },
  { alpha2: "FI", alpha3: "FIN", numeric: "246", aliases: ["finland", "finlandiya"] },
  { alpha2: "FR", alpha3: "FRA", numeric: "250", aliases: ["fransa"] },
  { alpha2: "GA", alpha3: "GAB", numeric: "266" },
  { alpha2: "GM", alpha3: "GMB", numeric: "270" },
  { alpha2: "GE", alpha3: "GEO", numeric: "268", aliases: ["georgia", "gurcistan"] },
  { alpha2: "DE", alpha3: "DEU", numeric: "276", aliases: ["germany", "almanya"] },
  { alpha2: "GH", alpha3: "GHA", numeric: "288" },
  { alpha2: "GR", alpha3: "GRC", numeric: "300", aliases: ["greece", "yunanistan"] },
  { alpha2: "GT", alpha3: "GTM", numeric: "320" },
  { alpha2: "GN", alpha3: "GIN", numeric: "324" },
  { alpha2: "GW", alpha3: "GNB", numeric: "624" },
  { alpha2: "GY", alpha3: "GUY", numeric: "328" },
  { alpha2: "HT", alpha3: "HTI", numeric: "332" },
  { alpha2: "HN", alpha3: "HND", numeric: "340" },
  { alpha2: "HU", alpha3: "HUN", numeric: "348", aliases: ["hungary", "macaristan"] },
  { alpha2: "IS", alpha3: "ISL", numeric: "352", aliases: ["iceland", "izlanda"] },
  { alpha2: "IN", alpha3: "IND", numeric: "356", aliases: ["india", "hindistan"] },
  { alpha2: "ID", alpha3: "IDN", numeric: "360", aliases: ["indonesia", "endonezya"] },
  { alpha2: "IR", alpha3: "IRN", numeric: "364", aliases: ["iran"] },
  { alpha2: "IQ", alpha3: "IRQ", numeric: "368", aliases: ["iraq", "irak"] },
  { alpha2: "IE", alpha3: "IRL", numeric: "372", aliases: ["ireland", "irlanda"] },
  { alpha2: "IL", alpha3: "ISR", numeric: "376", aliases: ["israel", "israil"] },
  { alpha2: "IT", alpha3: "ITA", numeric: "380", aliases: ["italy", "italya"] },
  { alpha2: "JM", alpha3: "JAM", numeric: "388" },
  { alpha2: "JP", alpha3: "JPN", numeric: "392", aliases: ["japan", "japonya"] },
  { alpha2: "JO", alpha3: "JOR", numeric: "400", aliases: ["jordan", "urdun"] },
  { alpha2: "KZ", alpha3: "KAZ", numeric: "398", aliases: ["kazakhstan", "kazakistan"] },
  { alpha2: "KE", alpha3: "KEN", numeric: "404" },
  { alpha2: "KR", alpha3: "KOR", numeric: "410", aliases: ["south korea", "korea", "guney kore"] },
  { alpha2: "KP", alpha3: "PRK", numeric: "408", aliases: ["north korea", "kuzey kore"] },
  { alpha2: "KW", alpha3: "KWT", numeric: "414", aliases: ["kuwait", "kuveyt"] },
  { alpha2: "KG", alpha3: "KGZ", numeric: "417", aliases: ["kyrgyzstan", "kirgizistan"] },
  { alpha2: "LA", alpha3: "LAO", numeric: "418" },
  { alpha2: "LV", alpha3: "LVA", numeric: "428", aliases: ["latvia", "letonya"] },
  { alpha2: "LB", alpha3: "LBN", numeric: "422", aliases: ["lebanon", "lubnan"] },
  { alpha2: "LS", alpha3: "LSO", numeric: "426" },
  { alpha2: "LR", alpha3: "LBR", numeric: "430" },
  { alpha2: "LY", alpha3: "LBY", numeric: "434", aliases: ["libya", "libya"] },
  { alpha2: "LI", alpha3: "LIE", numeric: "438" },
  { alpha2: "LT", alpha3: "LTU", numeric: "440", aliases: ["lithuania", "litvanya"] },
  { alpha2: "LU", alpha3: "LUX", numeric: "442" },
  { alpha2: "MG", alpha3: "MDG", numeric: "450", aliases: ["madagaskar"] },
  { alpha2: "MW", alpha3: "MWI", numeric: "454" },
  { alpha2: "MY", alpha3: "MYS", numeric: "458", aliases: ["malaysia", "malezya"] },
  { alpha2: "ML", alpha3: "MLI", numeric: "466" },
  { alpha2: "MT", alpha3: "MLT", numeric: "470" },
  { alpha2: "MR", alpha3: "MRT", numeric: "478" },
  { alpha2: "MU", alpha3: "MUS", numeric: "480" },
  { alpha2: "MX", alpha3: "MEX", numeric: "484", aliases: ["mexico", "meksika"] },
  { alpha2: "MD", alpha3: "MDA", numeric: "498", aliases: ["moldova"] },
  { alpha2: "MN", alpha3: "MNG", numeric: "496", aliases: ["mongolia", "mogolistan"] },
  { alpha2: "ME", alpha3: "MNE", numeric: "499", aliases: ["montenegro", "karadag"] },
  { alpha2: "MA", alpha3: "MAR", numeric: "504", aliases: ["morocco", "fas"] },
  { alpha2: "MZ", alpha3: "MOZ", numeric: "508" },
  { alpha2: "MM", alpha3: "MMR", numeric: "104", aliases: ["myanmar", "burma"] },
  { alpha2: "NA", alpha3: "NAM", numeric: "516" },
  { alpha2: "NP", alpha3: "NPL", numeric: "524", aliases: ["nepal"] },
  {
    alpha2: "NL",
    alpha3: "NLD",
    numeric: "528",
    aliases: ["netherlands", "the netherlands", "holland", "hollanda"],
  },
  { alpha2: "NZ", alpha3: "NZL", numeric: "554", aliases: ["new zealand", "yeni zelanda"] },
  { alpha2: "NI", alpha3: "NIC", numeric: "558" },
  { alpha2: "NE", alpha3: "NER", numeric: "562" },
  { alpha2: "NG", alpha3: "NGA", numeric: "566", aliases: ["nigeria", "nijerya"] },
  {
    alpha2: "MK",
    alpha3: "MKD",
    numeric: "807",
    aliases: ["north macedonia", "macedonia", "kuzey makedonya", "makedonya"],
  },
  { alpha2: "NO", alpha3: "NOR", numeric: "578", aliases: ["norway", "norvec"] },
  { alpha2: "OM", alpha3: "OMN", numeric: "512" },
  { alpha2: "PK", alpha3: "PAK", numeric: "586", aliases: ["pakistan"] },
  { alpha2: "PA", alpha3: "PAN", numeric: "591" },
  { alpha2: "PG", alpha3: "PNG", numeric: "598" },
  { alpha2: "PY", alpha3: "PRY", numeric: "600" },
  { alpha2: "PE", alpha3: "PER", numeric: "604", aliases: ["peru"] },
  { alpha2: "PH", alpha3: "PHL", numeric: "608", aliases: ["philippines", "filipinler"] },
  { alpha2: "PL", alpha3: "POL", numeric: "616", aliases: ["poland", "polonya"] },
  { alpha2: "PT", alpha3: "PRT", numeric: "620", aliases: ["portugal", "portekiz"] },
  { alpha2: "QA", alpha3: "QAT", numeric: "634", aliases: ["qatar", "katar"] },
  { alpha2: "RO", alpha3: "ROU", numeric: "642", aliases: ["romania", "romanya"] },
  { alpha2: "RU", alpha3: "RUS", numeric: "643", aliases: ["russia", "rusya"] },
  { alpha2: "RW", alpha3: "RWA", numeric: "646" },
  { alpha2: "SA", alpha3: "SAU", numeric: "682", aliases: ["saudi arabia", "suudi arabistan"] },
  { alpha2: "SN", alpha3: "SEN", numeric: "686" },
  { alpha2: "RS", alpha3: "SRB", numeric: "688", aliases: ["serbia", "sirbistan"] },
  { alpha2: "SL", alpha3: "SLE", numeric: "694" },
  { alpha2: "SG", alpha3: "SGP", numeric: "702", aliases: ["singapore", "singapur"] },
  { alpha2: "SK", alpha3: "SVK", numeric: "703", aliases: ["slovakia", "slovakya"] },
  { alpha2: "SI", alpha3: "SVN", numeric: "705", aliases: ["slovenia", "slovenya"] },
  { alpha2: "SO", alpha3: "SOM", numeric: "706", aliases: ["somalia", "somali"] },
  { alpha2: "ZA", alpha3: "ZAF", numeric: "710", aliases: ["south africa", "guney afrika"] },
  { alpha2: "ES", alpha3: "ESP", numeric: "724", aliases: ["spain", "ispanya"] },
  { alpha2: "LK", alpha3: "LKA", numeric: "144", aliases: ["sri lanka"] },
  { alpha2: "SD", alpha3: "SDN", numeric: "729", aliases: ["sudan"] },
  { alpha2: "SE", alpha3: "SWE", numeric: "752", aliases: ["sweden", "isvec"] },
  { alpha2: "CH", alpha3: "CHE", numeric: "756", aliases: ["switzerland", "isvicre"] },
  { alpha2: "SY", alpha3: "SYR", numeric: "760", aliases: ["syria", "suriye"] },
  { alpha2: "TW", alpha3: "TWN", numeric: "158", aliases: ["taiwan", "tayvan"] },
  { alpha2: "TJ", alpha3: "TJK", numeric: "762", aliases: ["tajikistan", "tacikistan"] },
  { alpha2: "TZ", alpha3: "TZA", numeric: "834", aliases: ["tanzania", "tanzanya"] },
  { alpha2: "TH", alpha3: "THA", numeric: "764", aliases: ["thailand", "tayland"] },
  { alpha2: "TG", alpha3: "TGO", numeric: "768" },
  { alpha2: "TN", alpha3: "TUN", numeric: "788", aliases: ["tunisia", "tunus"] },
  { alpha2: "TR", alpha3: "TUR", numeric: "792", aliases: ["turkey", "turkiye", "türkiye"] },
  { alpha2: "TM", alpha3: "TKM", numeric: "795", aliases: ["turkmenistan"] },
  { alpha2: "UG", alpha3: "UGA", numeric: "800" },
  { alpha2: "UA", alpha3: "UKR", numeric: "804", aliases: ["ukraine", "ukrayna"] },
  {
    alpha2: "AE",
    alpha3: "ARE",
    numeric: "784",
    aliases: ["uae", "united arab emirates", "birlesik arap emirlikleri"],
  },
  {
    alpha2: "GB",
    alpha3: "GBR",
    numeric: "826",
    aliases: [
      "uk",
      "united kingdom",
      "great britain",
      "england",
      "britain",
      "ingiltere",
      "birlesik krallik",
    ],
  },
  {
    alpha2: "US",
    alpha3: "USA",
    numeric: "840",
    aliases: ["usa", "united states", "united states of america", "america", "abd", "amerika"],
  },
  { alpha2: "UY", alpha3: "URY", numeric: "858", aliases: ["uruguay", "uruguay"] },
  { alpha2: "UZ", alpha3: "UZB", numeric: "860", aliases: ["uzbekistan", "ozbekistan"] },
  { alpha2: "VE", alpha3: "VEN", numeric: "862", aliases: ["venezuela"] },
  { alpha2: "VN", alpha3: "VNM", numeric: "704", aliases: ["vietnam", "vietnam"] },
  { alpha2: "YE", alpha3: "YEM", numeric: "887", aliases: ["yemen"] },
  { alpha2: "ZM", alpha3: "ZMB", numeric: "894" },
  { alpha2: "ZW", alpha3: "ZWE", numeric: "716" },
];
