export type CountryRecord = {
  alpha2: string;
  alpha3: string;
  numeric: string;
  aliases?: string[];
  ccTld?: string;
};

export const countries: CountryRecord[] = [
  { alpha2: "AD", alpha3: "AND", numeric: "020" },
  {
    alpha2: "AE",
    alpha3: "ARE",
    numeric: "784",
    aliases: ["uae", "united arab emirates", "birlesik arap emirlikleri"],
  },
  { alpha2: "AF", alpha3: "AFG", numeric: "004" },
  {
    alpha2: "AG",
    alpha3: "ATG",
    numeric: "028",
    aliases: ["antigua", "antigua and barbuda", "antigua ve barbuda"],
  },
  { alpha2: "AI", alpha3: "AIA", numeric: "660", aliases: ["anguilla"], ccTld: "ai" },
  { alpha2: "AL", alpha3: "ALB", numeric: "008" },
  { alpha2: "AM", alpha3: "ARM", numeric: "051" },
  { alpha2: "AO", alpha3: "AGO", numeric: "024" },
  {
    alpha2: "AQ",
    alpha3: "ATA",
    numeric: "010",
    aliases: ["antarctica", "antarktika", "antarctic"],
    ccTld: "aq",
  },
  { alpha2: "AR", alpha3: "ARG", numeric: "032" },
  {
    alpha2: "AS",
    alpha3: "ASM",
    numeric: "016",
    aliases: ["american samoa", "amerikan samoasi"],
    ccTld: "as",
  },
  { alpha2: "AT", alpha3: "AUT", numeric: "040", aliases: ["austria", "avusturya"] },
  { alpha2: "AU", alpha3: "AUS", numeric: "036", aliases: ["aussie", "australya"] },
  { alpha2: "AW", alpha3: "ABW", numeric: "533", aliases: ["aruba"], ccTld: "aw" },
  {
    alpha2: "AX",
    alpha3: "ALA",
    numeric: "248",
    aliases: ["aland", "aland islands", "åland"],
    ccTld: "ax",
  },
  { alpha2: "AZ", alpha3: "AZE", numeric: "031", aliases: ["azerbaycan"] },
  { alpha2: "BA", alpha3: "BIH", numeric: "070", aliases: ["bosnia", "bosna", "bosna hersek"] },
  { alpha2: "BB", alpha3: "BRB", numeric: "052", aliases: ["barbados"] },
  { alpha2: "BD", alpha3: "BGD", numeric: "050" },
  { alpha2: "BE", alpha3: "BEL", numeric: "056" },
  { alpha2: "BF", alpha3: "BFA", numeric: "854" },
  { alpha2: "BG", alpha3: "BGR", numeric: "100", aliases: ["bulgaristan"] },
  { alpha2: "BH", alpha3: "BHR", numeric: "048" },
  { alpha2: "BI", alpha3: "BDI", numeric: "108" },
  { alpha2: "BJ", alpha3: "BEN", numeric: "204" },
  {
    alpha2: "BL",
    alpha3: "BLM",
    numeric: "652",
    aliases: ["saint barthelemy", "st barthelemy", "st barths"],
    ccTld: "bl",
  },
  { alpha2: "BM", alpha3: "BMU", numeric: "060", aliases: ["bermuda"], ccTld: "bm" },
  { alpha2: "BN", alpha3: "BRN", numeric: "096" },
  { alpha2: "BO", alpha3: "BOL", numeric: "068" },
  {
    alpha2: "BQ",
    alpha3: "BES",
    numeric: "535",
    aliases: ["caribbean netherlands", "bonaire", "sint eustatius", "saba", "karayip hollandasi"],
    ccTld: "bq",
  },
  { alpha2: "BR", alpha3: "BRA", numeric: "076", aliases: ["brezilya"] },
  { alpha2: "BS", alpha3: "BHS", numeric: "044" },
  { alpha2: "BT", alpha3: "BTN", numeric: "064" },
  { alpha2: "BW", alpha3: "BWA", numeric: "072" },
  { alpha2: "BY", alpha3: "BLR", numeric: "112", aliases: ["belarus", "beyaz rusya"] },
  { alpha2: "BZ", alpha3: "BLZ", numeric: "084" },
  { alpha2: "CA", alpha3: "CAN", numeric: "124", aliases: ["kanada"] },
  {
    alpha2: "CC",
    alpha3: "CCK",
    numeric: "166",
    aliases: ["cocos islands", "cocos keeling islands", "keeling islands"],
    ccTld: "cc",
  },
  {
    alpha2: "CD",
    alpha3: "COD",
    numeric: "180",
    aliases: ["dr congo", "democratic republic of congo", "kongo demokratik cumhuriyeti"],
  },
  { alpha2: "CF", alpha3: "CAF", numeric: "140" },
  { alpha2: "CG", alpha3: "COG", numeric: "178", aliases: ["congo"] },
  { alpha2: "CH", alpha3: "CHE", numeric: "756", aliases: ["switzerland", "isvicre"] },
  {
    alpha2: "CI",
    alpha3: "CIV",
    numeric: "384",
    aliases: ["ivory coast", "cote divoire", "cote d ivoire", "fildisi sahili"],
  },
  {
    alpha2: "CK",
    alpha3: "COK",
    numeric: "184",
    aliases: ["cook islands", "cook adalari"],
    ccTld: "ck",
  },
  { alpha2: "CL", alpha3: "CHL", numeric: "152", aliases: ["sili"] },
  { alpha2: "CM", alpha3: "CMR", numeric: "120" },
  { alpha2: "CN", alpha3: "CHN", numeric: "156", aliases: ["china", "cin"] },
  { alpha2: "CO", alpha3: "COL", numeric: "170", aliases: ["kolombiya"] },
  { alpha2: "CR", alpha3: "CRI", numeric: "188", aliases: ["kosta rika"] },
  { alpha2: "CU", alpha3: "CUB", numeric: "192" },
  { alpha2: "CV", alpha3: "CPV", numeric: "132" },
  { alpha2: "CW", alpha3: "CUW", numeric: "531", aliases: ["curacao", "curaçao"], ccTld: "cw" },
  {
    alpha2: "CX",
    alpha3: "CXR",
    numeric: "162",
    aliases: ["christmas island", "christmas adasi"],
    ccTld: "cx",
  },
  { alpha2: "CY", alpha3: "CYP", numeric: "196", aliases: ["kibris", "cyprus"] },
  {
    alpha2: "CZ",
    alpha3: "CZE",
    numeric: "203",
    aliases: ["czechia", "czech republic", "cekya", "cek cumhuriyeti"],
  },
  { alpha2: "DE", alpha3: "DEU", numeric: "276", aliases: ["germany", "almanya"] },
  { alpha2: "DJ", alpha3: "DJI", numeric: "262" },
  { alpha2: "DK", alpha3: "DNK", numeric: "208", aliases: ["denmark", "danimarka"] },
  { alpha2: "DM", alpha3: "DMA", numeric: "212", aliases: ["dominica", "dominika"] },
  { alpha2: "DO", alpha3: "DOM", numeric: "214" },
  { alpha2: "DZ", alpha3: "DZA", numeric: "012" },
  { alpha2: "EC", alpha3: "ECU", numeric: "218", aliases: ["ekvador"] },
  { alpha2: "EE", alpha3: "EST", numeric: "233", aliases: ["estonya"] },
  { alpha2: "EG", alpha3: "EGY", numeric: "818", aliases: ["misir"] },
  { alpha2: "EH", alpha3: "ESH", numeric: "732", aliases: ["western sahara", "bati sahara"] },
  { alpha2: "ER", alpha3: "ERI", numeric: "232" },
  { alpha2: "ES", alpha3: "ESP", numeric: "724", aliases: ["spain", "ispanya"] },
  { alpha2: "ET", alpha3: "ETH", numeric: "231", aliases: ["ethiopia", "etiyopya"] },
  { alpha2: "FI", alpha3: "FIN", numeric: "246", aliases: ["finland", "finlandiya"] },
  { alpha2: "FJ", alpha3: "FJI", numeric: "242" },
  {
    alpha2: "FK",
    alpha3: "FLK",
    numeric: "238",
    aliases: ["falkland islands", "falkland", "falkland adalari", "malvinas"],
    ccTld: "fk",
  },
  { alpha2: "FM", alpha3: "FSM", numeric: "583", aliases: ["micronesia", "mikronezya"] },
  {
    alpha2: "FO",
    alpha3: "FRO",
    numeric: "234",
    aliases: ["faroe islands", "faroe", "faroe adalari"],
    ccTld: "fo",
  },
  { alpha2: "FR", alpha3: "FRA", numeric: "250", aliases: ["fransa"] },
  { alpha2: "GA", alpha3: "GAB", numeric: "266" },
  {
    alpha2: "GB",
    alpha3: "GBR",
    numeric: "826",
    aliases: [
      "uk",
      "united kingdom",
      "great britain",
      "england",
      "britain",
      "ingiltere",
      "birlesik krallik",
    ],
  },
  { alpha2: "GD", alpha3: "GRD", numeric: "308", aliases: ["grenada"] },
  { alpha2: "GE", alpha3: "GEO", numeric: "268", aliases: ["georgia", "gurcistan"] },
  {
    alpha2: "GF",
    alpha3: "GUF",
    numeric: "254",
    aliases: ["french guiana", "fransiz guyanasi"],
    ccTld: "gf",
  },
  { alpha2: "GG", alpha3: "GGY", numeric: "831", aliases: ["guernsey"], ccTld: "gg" },
  { alpha2: "GH", alpha3: "GHA", numeric: "288" },
  {
    alpha2: "GI",
    alpha3: "GIB",
    numeric: "292",
    aliases: ["gibraltar", "cebelitarik"],
    ccTld: "gi",
  },
  { alpha2: "GL", alpha3: "GRL", numeric: "304", aliases: ["greenland", "gronland"], ccTld: "gl" },
  { alpha2: "GM", alpha3: "GMB", numeric: "270" },
  { alpha2: "GN", alpha3: "GIN", numeric: "324" },
  { alpha2: "GP", alpha3: "GLP", numeric: "312", aliases: ["guadeloupe"], ccTld: "gp" },
  { alpha2: "GQ", alpha3: "GNQ", numeric: "226" },
  { alpha2: "GR", alpha3: "GRC", numeric: "300", aliases: ["greece", "yunanistan"] },
  {
    alpha2: "GS",
    alpha3: "SGS",
    numeric: "239",
    aliases: ["south georgia", "south georgia and the south sandwich islands"],
    ccTld: "gs",
  },
  { alpha2: "GT", alpha3: "GTM", numeric: "320" },
  { alpha2: "GU", alpha3: "GUM", numeric: "316", aliases: ["guam"], ccTld: "gu" },
  { alpha2: "GW", alpha3: "GNB", numeric: "624" },
  { alpha2: "GY", alpha3: "GUY", numeric: "328" },
  {
    alpha2: "HK",
    alpha3: "HKG",
    numeric: "344",
    aliases: ["hong kong", "hong kong sar"],
    ccTld: "hk",
  },
  { alpha2: "HN", alpha3: "HND", numeric: "340" },
  { alpha2: "HR", alpha3: "HRV", numeric: "191", aliases: ["croatia", "hirvatistan"] },
  { alpha2: "HT", alpha3: "HTI", numeric: "332" },
  { alpha2: "HU", alpha3: "HUN", numeric: "348", aliases: ["hungary", "macaristan"] },
  { alpha2: "ID", alpha3: "IDN", numeric: "360", aliases: ["indonesia", "endonezya"] },
  { alpha2: "IE", alpha3: "IRL", numeric: "372", aliases: ["ireland", "irlanda"] },
  { alpha2: "IL", alpha3: "ISR", numeric: "376", aliases: ["israel", "israil"] },
  {
    alpha2: "IM",
    alpha3: "IMN",
    numeric: "833",
    aliases: ["isle of man", "man adasi"],
    ccTld: "im",
  },
  { alpha2: "IN", alpha3: "IND", numeric: "356", aliases: ["india", "hindistan"] },
  {
    alpha2: "IO",
    alpha3: "IOT",
    numeric: "086",
    aliases: ["british indian ocean territory", "chagos"],
    ccTld: "io",
  },
  { alpha2: "IQ", alpha3: "IRQ", numeric: "368", aliases: ["iraq", "irak"] },
  { alpha2: "IR", alpha3: "IRN", numeric: "364", aliases: ["iran"] },
  { alpha2: "IS", alpha3: "ISL", numeric: "352", aliases: ["iceland", "izlanda"] },
  { alpha2: "IT", alpha3: "ITA", numeric: "380", aliases: ["italy", "italya"] },
  { alpha2: "JE", alpha3: "JEY", numeric: "832", aliases: ["jersey"], ccTld: "je" },
  { alpha2: "JM", alpha3: "JAM", numeric: "388" },
  { alpha2: "JO", alpha3: "JOR", numeric: "400", aliases: ["jordan", "urdun"] },
  { alpha2: "JP", alpha3: "JPN", numeric: "392", aliases: ["japan", "japonya"] },
  { alpha2: "KE", alpha3: "KEN", numeric: "404" },
  { alpha2: "KG", alpha3: "KGZ", numeric: "417", aliases: ["kyrgyzstan", "kirgizistan"] },
  { alpha2: "KH", alpha3: "KHM", numeric: "116", aliases: ["cambodia", "kambocya"] },
  { alpha2: "KI", alpha3: "KIR", numeric: "296", aliases: ["kiribati"] },
  { alpha2: "KM", alpha3: "COM", numeric: "174" },
  {
    alpha2: "KN",
    alpha3: "KNA",
    numeric: "659",
    aliases: ["saint kitts", "st kitts", "saint kitts and nevis", "st kitts and nevis"],
  },
  { alpha2: "KP", alpha3: "PRK", numeric: "408", aliases: ["north korea", "kuzey kore"] },
  { alpha2: "KR", alpha3: "KOR", numeric: "410", aliases: ["south korea", "korea", "guney kore"] },
  { alpha2: "KW", alpha3: "KWT", numeric: "414", aliases: ["kuwait", "kuveyt"] },
  {
    alpha2: "KY",
    alpha3: "CYM",
    numeric: "136",
    aliases: ["cayman islands", "cayman", "cayman adalari"],
    ccTld: "ky",
  },
  { alpha2: "KZ", alpha3: "KAZ", numeric: "398", aliases: ["kazakhstan", "kazakistan"] },
  { alpha2: "LA", alpha3: "LAO", numeric: "418" },
  { alpha2: "LB", alpha3: "LBN", numeric: "422", aliases: ["lebanon", "lubnan"] },
  { alpha2: "LC", alpha3: "LCA", numeric: "662", aliases: ["saint lucia", "st lucia"] },
  { alpha2: "LI", alpha3: "LIE", numeric: "438", aliases: ["liechtenstein", "lihtenştayn"] },
  { alpha2: "LK", alpha3: "LKA", numeric: "144", aliases: ["sri lanka"] },
  { alpha2: "LR", alpha3: "LBR", numeric: "430" },
  { alpha2: "LS", alpha3: "LSO", numeric: "426" },
  { alpha2: "LT", alpha3: "LTU", numeric: "440", aliases: ["lithuania", "litvanya"] },
  { alpha2: "LU", alpha3: "LUX", numeric: "442" },
  { alpha2: "LV", alpha3: "LVA", numeric: "428", aliases: ["latvia", "letonya"] },
  { alpha2: "LY", alpha3: "LBY", numeric: "434", aliases: ["libya", "libya"] },
  { alpha2: "MA", alpha3: "MAR", numeric: "504", aliases: ["morocco", "fas"] },
  { alpha2: "MC", alpha3: "MCO", numeric: "492", aliases: ["monaco", "monako"] },
  { alpha2: "MD", alpha3: "MDA", numeric: "498", aliases: ["moldova"] },
  { alpha2: "ME", alpha3: "MNE", numeric: "499", aliases: ["montenegro", "karadag"] },
  {
    alpha2: "MF",
    alpha3: "MAF",
    numeric: "663",
    aliases: ["saint martin", "st martin"],
    ccTld: "mf",
  },
  { alpha2: "MG", alpha3: "MDG", numeric: "450", aliases: ["madagaskar"] },
  {
    alpha2: "MH",
    alpha3: "MHL",
    numeric: "584",
    aliases: ["marshall islands", "marshall adalari"],
  },
  {
    alpha2: "MK",
    alpha3: "MKD",
    numeric: "807",
    aliases: ["north macedonia", "macedonia", "kuzey makedonya", "makedonya"],
  },
  { alpha2: "ML", alpha3: "MLI", numeric: "466" },
  { alpha2: "MM", alpha3: "MMR", numeric: "104", aliases: ["myanmar", "burma"] },
  { alpha2: "MN", alpha3: "MNG", numeric: "496", aliases: ["mongolia", "mogolistan"] },
  {
    alpha2: "MO",
    alpha3: "MAC",
    numeric: "446",
    aliases: ["macao", "macau", "makao"],
    ccTld: "mo",
  },
  {
    alpha2: "MP",
    alpha3: "MNP",
    numeric: "580",
    aliases: ["northern mariana islands", "kuzey mariana adalari"],
    ccTld: "mp",
  },
  { alpha2: "MQ", alpha3: "MTQ", numeric: "474", aliases: ["martinique", "martinik"], ccTld: "mq" },
  { alpha2: "MR", alpha3: "MRT", numeric: "478" },
  { alpha2: "MS", alpha3: "MSR", numeric: "500", aliases: ["montserrat"], ccTld: "ms" },
  { alpha2: "MT", alpha3: "MLT", numeric: "470" },
  { alpha2: "MU", alpha3: "MUS", numeric: "480" },
  { alpha2: "MV", alpha3: "MDV", numeric: "462", aliases: ["maldives", "maldivler"] },
  { alpha2: "MW", alpha3: "MWI", numeric: "454" },
  { alpha2: "MX", alpha3: "MEX", numeric: "484", aliases: ["mexico", "meksika"] },
  { alpha2: "MY", alpha3: "MYS", numeric: "458", aliases: ["malaysia", "malezya"] },
  { alpha2: "MZ", alpha3: "MOZ", numeric: "508" },
  { alpha2: "NA", alpha3: "NAM", numeric: "516" },
  {
    alpha2: "NC",
    alpha3: "NCL",
    numeric: "540",
    aliases: ["new caledonia", "yeni kaledonya"],
    ccTld: "nc",
  },
  { alpha2: "NE", alpha3: "NER", numeric: "562" },
  {
    alpha2: "NF",
    alpha3: "NFK",
    numeric: "574",
    aliases: ["norfolk island", "norfolk adasi"],
    ccTld: "nf",
  },
  { alpha2: "NG", alpha3: "NGA", numeric: "566", aliases: ["nigeria", "nijerya"] },
  { alpha2: "NI", alpha3: "NIC", numeric: "558" },
  {
    alpha2: "NL",
    alpha3: "NLD",
    numeric: "528",
    aliases: ["netherlands", "the netherlands", "holland", "hollanda"],
  },
  { alpha2: "NO", alpha3: "NOR", numeric: "578", aliases: ["norway", "norvec"] },
  { alpha2: "NP", alpha3: "NPL", numeric: "524", aliases: ["nepal"] },
  { alpha2: "NR", alpha3: "NRU", numeric: "520", aliases: ["nauru"] },
  { alpha2: "NU", alpha3: "NIU", numeric: "570", aliases: ["niue"], ccTld: "nu" },
  { alpha2: "NZ", alpha3: "NZL", numeric: "554", aliases: ["new zealand", "yeni zelanda"] },
  { alpha2: "OM", alpha3: "OMN", numeric: "512" },
  { alpha2: "PA", alpha3: "PAN", numeric: "591" },
  { alpha2: "PE", alpha3: "PER", numeric: "604", aliases: ["peru"] },
  {
    alpha2: "PF",
    alpha3: "PYF",
    numeric: "258",
    aliases: ["french polynesia", "fransiz polinezyasi", "tahiti"],
    ccTld: "pf",
  },
  { alpha2: "PG", alpha3: "PNG", numeric: "598" },
  { alpha2: "PH", alpha3: "PHL", numeric: "608", aliases: ["philippines", "filipinler"] },
  { alpha2: "PK", alpha3: "PAK", numeric: "586", aliases: ["pakistan"] },
  { alpha2: "PL", alpha3: "POL", numeric: "616", aliases: ["poland", "polonya"] },
  {
    alpha2: "PM",
    alpha3: "SPM",
    numeric: "666",
    aliases: ["saint pierre and miquelon", "st pierre and miquelon"],
    ccTld: "pm",
  },
  {
    alpha2: "PN",
    alpha3: "PCN",
    numeric: "612",
    aliases: ["pitcairn", "pitcairn islands"],
    ccTld: "pn",
  },
  {
    alpha2: "PR",
    alpha3: "PRI",
    numeric: "630",
    aliases: ["puerto rico", "porto rico", "porto riko"],
    ccTld: "pr",
  },
  {
    alpha2: "PS",
    alpha3: "PSE",
    numeric: "275",
    aliases: ["palestine", "filistin", "palestinian territories"],
  },
  { alpha2: "PT", alpha3: "PRT", numeric: "620", aliases: ["portugal", "portekiz"] },
  { alpha2: "PW", alpha3: "PLW", numeric: "585", aliases: ["palau"] },
  { alpha2: "PY", alpha3: "PRY", numeric: "600" },
  { alpha2: "QA", alpha3: "QAT", numeric: "634", aliases: ["qatar", "katar"] },
  { alpha2: "RE", alpha3: "REU", numeric: "638", aliases: ["reunion", "réunion"], ccTld: "re" },
  { alpha2: "RO", alpha3: "ROU", numeric: "642", aliases: ["romania", "romanya"] },
  { alpha2: "RS", alpha3: "SRB", numeric: "688", aliases: ["serbia", "sirbistan"] },
  { alpha2: "RU", alpha3: "RUS", numeric: "643", aliases: ["russia", "rusya"] },
  { alpha2: "RW", alpha3: "RWA", numeric: "646" },
  { alpha2: "SA", alpha3: "SAU", numeric: "682", aliases: ["saudi arabia", "suudi arabistan"] },
  { alpha2: "SB", alpha3: "SLB", numeric: "090", aliases: ["solomon islands", "solomon adalari"] },
  { alpha2: "SC", alpha3: "SYC", numeric: "690", aliases: ["seychelles", "seyseller"] },
  { alpha2: "SD", alpha3: "SDN", numeric: "729", aliases: ["sudan"] },
  { alpha2: "SE", alpha3: "SWE", numeric: "752", aliases: ["sweden", "isvec"] },
  { alpha2: "SG", alpha3: "SGP", numeric: "702", aliases: ["singapore", "singapur"] },
  {
    alpha2: "SH",
    alpha3: "SHN",
    numeric: "654",
    aliases: ["saint helena", "st helena", "ascension", "tristan da cunha"],
    ccTld: "sh",
  },
  { alpha2: "SI", alpha3: "SVN", numeric: "705", aliases: ["slovenia", "slovenya"] },
  { alpha2: "SK", alpha3: "SVK", numeric: "703", aliases: ["slovakia", "slovakya"] },
  { alpha2: "SL", alpha3: "SLE", numeric: "694" },
  { alpha2: "SM", alpha3: "SMR", numeric: "674", aliases: ["san marino"] },
  { alpha2: "SN", alpha3: "SEN", numeric: "686" },
  { alpha2: "SO", alpha3: "SOM", numeric: "706", aliases: ["somalia", "somali"] },
  { alpha2: "SR", alpha3: "SUR", numeric: "740", aliases: ["suriname", "surinam"] },
  { alpha2: "SS", alpha3: "SSD", numeric: "728", aliases: ["south sudan", "guney sudan"] },
  { alpha2: "ST", alpha3: "STP", numeric: "678", aliases: ["sao tome", "sao tome and principe"] },
  { alpha2: "SV", alpha3: "SLV", numeric: "222" },
  { alpha2: "SX", alpha3: "SXM", numeric: "534", aliases: ["sint maarten"], ccTld: "sx" },
  { alpha2: "SY", alpha3: "SYR", numeric: "760", aliases: ["syria", "suriye"] },
  { alpha2: "SZ", alpha3: "SWZ", numeric: "748", aliases: ["eswatini", "swaziland"] },
  {
    alpha2: "TC",
    alpha3: "TCA",
    numeric: "796",
    aliases: ["turks and caicos", "turks and caicos islands"],
    ccTld: "tc",
  },
  { alpha2: "TD", alpha3: "TCD", numeric: "148", aliases: ["chad", "cad"] },
  {
    alpha2: "TF",
    alpha3: "ATF",
    numeric: "260",
    aliases: ["french southern territories", "fransiz guney topraklari"],
    ccTld: "tf",
  },
  { alpha2: "TG", alpha3: "TGO", numeric: "768" },
  { alpha2: "TH", alpha3: "THA", numeric: "764", aliases: ["thailand", "tayland"] },
  { alpha2: "TJ", alpha3: "TJK", numeric: "762", aliases: ["tajikistan", "tacikistan"] },
  { alpha2: "TK", alpha3: "TKL", numeric: "772", aliases: ["tokelau"], ccTld: "tk" },
  {
    alpha2: "TL",
    alpha3: "TLS",
    numeric: "626",
    aliases: ["timor leste", "east timor", "dogu timor"],
  },
  { alpha2: "TM", alpha3: "TKM", numeric: "795", aliases: ["turkmenistan"] },
  { alpha2: "TN", alpha3: "TUN", numeric: "788", aliases: ["tunisia", "tunus"] },
  { alpha2: "TO", alpha3: "TON", numeric: "776", aliases: ["tonga"] },
  { alpha2: "TR", alpha3: "TUR", numeric: "792", aliases: ["turkey", "turkiye", "türkiye"] },
  {
    alpha2: "TT",
    alpha3: "TTO",
    numeric: "780",
    aliases: ["trinidad", "trinidad and tobago", "trinidad ve tobago"],
  },
  { alpha2: "TV", alpha3: "TUV", numeric: "798", aliases: ["tuvalu"] },
  { alpha2: "TW", alpha3: "TWN", numeric: "158", aliases: ["taiwan", "tayvan"] },
  { alpha2: "TZ", alpha3: "TZA", numeric: "834", aliases: ["tanzania", "tanzanya"] },
  { alpha2: "UA", alpha3: "UKR", numeric: "804", aliases: ["ukraine", "ukrayna"] },
  { alpha2: "UG", alpha3: "UGA", numeric: "800" },
  {
    alpha2: "US",
    alpha3: "USA",
    numeric: "840",
    aliases: ["usa", "united states", "united states of america", "america", "abd", "amerika"],
  },
  { alpha2: "UY", alpha3: "URY", numeric: "858", aliases: ["uruguay", "uruguay"] },
  { alpha2: "UZ", alpha3: "UZB", numeric: "860", aliases: ["uzbekistan", "ozbekistan"] },
  {
    alpha2: "VA",
    alpha3: "VAT",
    numeric: "336",
    aliases: ["vatican", "vatican city", "vatikan", "holy see"],
  },
  {
    alpha2: "VC",
    alpha3: "VCT",
    numeric: "670",
    aliases: ["saint vincent", "st vincent", "saint vincent and the grenadines"],
  },
  { alpha2: "VE", alpha3: "VEN", numeric: "862", aliases: ["venezuela"] },
  {
    alpha2: "VG",
    alpha3: "VGB",
    numeric: "092",
    aliases: ["british virgin islands", "britanya virjin adalari"],
    ccTld: "vg",
  },
  {
    alpha2: "VI",
    alpha3: "VIR",
    numeric: "850",
    aliases: ["us virgin islands", "u.s. virgin islands", "abd virjin adalari"],
    ccTld: "vi",
  },
  { alpha2: "VN", alpha3: "VNM", numeric: "704", aliases: ["vietnam", "vietnam"] },
  { alpha2: "VU", alpha3: "VUT", numeric: "548", aliases: ["vanuatu"] },
  {
    alpha2: "WF",
    alpha3: "WLF",
    numeric: "876",
    aliases: ["wallis and futuna", "wallis ve futuna"],
    ccTld: "wf",
  },
  { alpha2: "WS", alpha3: "WSM", numeric: "882", aliases: ["samoa"] },
  { alpha2: "XK", alpha3: "XKX", numeric: "983", aliases: ["kosovo", "kosova"] },
  { alpha2: "YE", alpha3: "YEM", numeric: "887", aliases: ["yemen"] },
  { alpha2: "YT", alpha3: "MYT", numeric: "175", aliases: ["mayotte"], ccTld: "yt" },
  { alpha2: "ZA", alpha3: "ZAF", numeric: "710", aliases: ["south africa", "guney afrika"] },
  { alpha2: "ZM", alpha3: "ZMB", numeric: "894" },
  { alpha2: "ZW", alpha3: "ZWE", numeric: "716" },
];
