export type ContinentCode = "AF" | "AS" | "EU" | "NA" | "SA" | "OC" | "AN";

export const CONTINENTS: ContinentCode[] = ["AF", "AS", "EU", "NA", "SA", "OC", "AN"];

/** Overseas / territory country codes for `territory_win`. */
export const TERRITORY_COUNTRY_CODES = new Set([
  "RE",
  "GP",
  "MQ",
  "GF",
  "YT",
  "NC",
  "PF",
  "BL",
  "MF",
  "PM",
  "TF",
  "WF",
  "PR",
  "VI",
  "GU",
  "AS",
  "MP",
  "HK",
  "MO",
  "AW",
  "CW",
  "SX",
  "BQ",
  "GL",
  "FO",
  "AX",
  "CC",
  "CX",
  "NF",
  "CK",
  "NU",
  "TK",
  "AQ",
]);

export const isTerritoryCountry = (countryCode: string) =>
  TERRITORY_COUNTRY_CODES.has(countryCode.toUpperCase());

/**
 * Compact ISO 3166-1 alpha-2 → continent map for achievements.
 * Unknown codes return undefined (do not count toward continent tour).
 */
const COUNTRY_CONTINENT: Record<string, ContinentCode> = {
  // Africa
  DZ: "AF",
  AO: "AF",
  BJ: "AF",
  BW: "AF",
  BF: "AF",
  BI: "AF",
  CV: "AF",
  CM: "AF",
  CF: "AF",
  TD: "AF",
  KM: "AF",
  CG: "AF",
  CD: "AF",
  CI: "AF",
  DJ: "AF",
  EG: "AF",
  GQ: "AF",
  ER: "AF",
  SZ: "AF",
  ET: "AF",
  GA: "AF",
  GM: "AF",
  GH: "AF",
  GN: "AF",
  GW: "AF",
  KE: "AF",
  LS: "AF",
  LR: "AF",
  LY: "AF",
  MG: "AF",
  MW: "AF",
  ML: "AF",
  MR: "AF",
  MU: "AF",
  YT: "AF",
  MA: "AF",
  MZ: "AF",
  NA: "AF",
  NE: "AF",
  NG: "AF",
  RE: "AF",
  RW: "AF",
  ST: "AF",
  SN: "AF",
  SC: "AF",
  SL: "AF",
  SO: "AF",
  ZA: "AF",
  SS: "AF",
  SD: "AF",
  TZ: "AF",
  TG: "AF",
  TN: "AF",
  UG: "AF",
  EH: "AF",
  ZM: "AF",
  ZW: "AF",
  // Asia
  AF: "AS",
  AM: "AS",
  AZ: "AS",
  BH: "AS",
  BD: "AS",
  BT: "AS",
  BN: "AS",
  KH: "AS",
  CN: "AS",
  CY: "AS",
  GE: "AS",
  HK: "AS",
  IN: "AS",
  ID: "AS",
  IR: "AS",
  IQ: "AS",
  IL: "AS",
  JP: "AS",
  JO: "AS",
  KZ: "AS",
  KW: "AS",
  KG: "AS",
  LA: "AS",
  LB: "AS",
  MO: "AS",
  MY: "AS",
  MV: "AS",
  MN: "AS",
  MM: "AS",
  NP: "AS",
  KP: "AS",
  OM: "AS",
  PK: "AS",
  PS: "AS",
  PH: "AS",
  QA: "AS",
  SA: "AS",
  SG: "AS",
  KR: "AS",
  LK: "AS",
  SY: "AS",
  TW: "AS",
  TJ: "AS",
  TH: "AS",
  TL: "AS",
  TR: "AS",
  TM: "AS",
  AE: "AS",
  UZ: "AS",
  VN: "AS",
  YE: "AS",
  // Europe
  AL: "EU",
  AD: "EU",
  AT: "EU",
  BY: "EU",
  BE: "EU",
  BA: "EU",
  BG: "EU",
  HR: "EU",
  CZ: "EU",
  DK: "EU",
  EE: "EU",
  FO: "EU",
  FI: "EU",
  FR: "EU",
  DE: "EU",
  GI: "EU",
  GR: "EU",
  GG: "EU",
  HU: "EU",
  IS: "EU",
  IE: "EU",
  IM: "EU",
  IT: "EU",
  JE: "EU",
  XK: "EU",
  LV: "EU",
  LI: "EU",
  LT: "EU",
  LU: "EU",
  MT: "EU",
  MD: "EU",
  MC: "EU",
  ME: "EU",
  NL: "EU",
  MK: "EU",
  NO: "EU",
  PL: "EU",
  PT: "EU",
  RO: "EU",
  RU: "EU",
  SM: "EU",
  RS: "EU",
  SK: "EU",
  SI: "EU",
  ES: "EU",
  SE: "EU",
  CH: "EU",
  UA: "EU",
  GB: "EU",
  VA: "EU",
  AX: "EU",
  // North America
  AG: "NA",
  BS: "NA",
  BB: "NA",
  BZ: "NA",
  CA: "NA",
  CR: "NA",
  CU: "NA",
  DM: "NA",
  DO: "NA",
  SV: "NA",
  GD: "NA",
  GT: "NA",
  HT: "NA",
  HN: "NA",
  JM: "NA",
  MX: "NA",
  NI: "NA",
  PA: "NA",
  KN: "NA",
  LC: "NA",
  VC: "NA",
  TT: "NA",
  US: "NA",
  PR: "NA",
  VI: "NA",
  GU: "OC", // Pacific territory — count as Oceania for tour completeness of US territories
  AS: "OC",
  MP: "OC",
  GL: "NA",
  BM: "NA",
  KY: "NA",
  TC: "NA",
  VG: "NA",
  AW: "NA",
  CW: "NA",
  SX: "NA",
  BQ: "NA",
  MF: "NA",
  BL: "NA",
  PM: "NA",
  // South America
  AR: "SA",
  BO: "SA",
  BR: "SA",
  CL: "SA",
  CO: "SA",
  EC: "SA",
  FK: "SA",
  GF: "SA",
  GY: "SA",
  PY: "SA",
  PE: "SA",
  SR: "SA",
  UY: "SA",
  VE: "SA",
  // Oceania
  AU: "OC",
  FJ: "OC",
  KI: "OC",
  MH: "OC",
  FM: "OC",
  NR: "OC",
  NZ: "OC",
  PW: "OC",
  PG: "OC",
  WS: "OC",
  SB: "OC",
  TO: "OC",
  TV: "OC",
  VU: "OC",
  NC: "OC",
  PF: "OC",
  WF: "OC",
  CK: "OC",
  NU: "OC",
  TK: "OC",
  CC: "OC",
  CX: "OC",
  NF: "OC",
  // Antarctica
  AQ: "AN",
  TF: "AN",
  GS: "AN",
  BV: "AN",
  HM: "AN",
};

export const continentForCountry = (countryCode: string): ContinentCode | undefined =>
  COUNTRY_CONTINENT[countryCode.toUpperCase()];

export const hasAllContinents = (countryCodes: Iterable<string>) => {
  const found = new Set<ContinentCode>();
  for (const code of countryCodes) {
    const continent = continentForCountry(code);
    if (continent) {
      found.add(continent);
    }
  }
  return CONTINENTS.every((continent) => found.has(continent));
};
